# Exercices NumPy

Maintenant que nous avons découvert NumPy, nous allons tester vos connaissances. Nous allons commencer par quelques tâches simples, puis nous vous poserons des questions plus complexes.

<div class="alert alert-danger" style="margin: 10px"><strong>NOTE IMPORTANTE !</strong> Assurez-vous de ne pas exécuter les cellules directement au-dessus de l'exemple de résultat affiché, autrement vous écrirez par dessus ce résultat attendu (et devrez aller chercher de nouveau le notebook du cours ou regarder la correction) !</div>

## 1. Import NumPy as np

In [ ]:
import numpy as np

## 2. Créer un tableau de 10 zéros

In [3]:

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Ne pas exécuter cette cellule

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3. Créer un tableau de 10 uns

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Ne pas exécuter cette cellule

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 4. Créer un tableau de 10 cinq

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Ne pas exécuter cette cellule

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Créer un tableau des nombres entiers de 10 à 50

In [6]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Ne pas exécuter cette cellule

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## 6. Créer un tableau de tous les entiers pairs de 10 à 50

In [7]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
# Ne pas exécuter cette cellule

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## 7. Créer une matrice 3x3 avec des valeurs allant de 0 à 8

In [8]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Ne pas exécuter cette cellule

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 8. Créer une matrice d'identité 3x3

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Ne pas exécuter cette cellule

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 9. Utiliser NumPy pour générer un nombre aléatoire entre 0 et 1

NOTE : La valeur de votre résultat devrait être différente de celle indiquée ci-dessous.

In [10]:
np.random.random()

0.7903253747475665

In [ ]:
# Ne pas exécuter cette cellule

array([0.65248055])

## 10. Utiliser NumPy pour générer un tableau de 25 nombres aléatoires tirés d'une distribution normale standard.

NOTE : Les valeurs de votre résultat devraient être différentes de celles indiquées ci-dessous.

In [11]:
np.random.randn(25)

array([-0.24992655, -1.58710388,  1.15476346,  0.89591348, -0.65737007,
        0.67093912,  0.29344492, -0.6617556 , -0.02414114, -2.25080173,
       -0.13909483, -1.56981591, -0.7011436 ,  1.77089136, -1.93867138,
        0.26827907,  0.14162238,  0.01502828,  0.27295458,  1.60532915,
       -0.77715203,  0.45653817, -0.22705515,  0.77923979, -0.94651093])

In [ ]:
# Ne pas exécuter cette cellule

array([ 0.09383799, -0.52935636, -1.25121675,  1.16722582, -1.55552581,
       -0.86892507, -0.15017841, -0.23712272,  0.43718044,  0.14334489,
       -0.1974204 ,  0.32470701, -0.47640942,  0.82524833, -0.28739026,
       -0.91433916,  1.90245017,  0.32386353, -0.42055596, -1.87368848,
       -0.16755609,  1.58759932, -0.75185054, -0.27830683, -0.65479306])

## 11. Créer la matrice suivante

In [12]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
# Ne pas exécuter cette cellule

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## 12. Créer un tableau de 20 points linéairement espacés entre 0 et 1

In [13]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Ne pas exécuter cette cellule

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexation et sélection NumPy

On vous donne maintenant une matrice de départ (n'oubliez pas d'exécuter la cellule ci-dessous !), et on vous demande de reproduire les sorties de la matrice résultante

In [14]:
# EXÉCUTER CETTE CELLULE - C'EST NOTRE MATRICE DE DÉPART
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 13. Écrire un code qui reproduit la sortie indiquée ci-dessous

Faites attention à ne pas exécuter la cellule immédiatement au-dessus de la sortie, sinon vous ne pourrez plus voir la sortie attendue.

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat[2:6, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Ne pas exécuter cette cellule

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### 14. Écrire le code qui reproduit la sortie montrée ci-dessous

In [16]:
mat[3][4]

20

In [ ]:
# Ne pas exécuter cette cellule

20

### 15. Écrire le code qui reproduit la sortie montrée ci-dessous

In [18]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# ne pas exécuter cette cellule

array([[ 2],
       [ 7],
       [12]])

### 16. Écrire le code qui reproduit la sortie montrée ci-dessous

In [19]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# Ne pas exécuter cette cellule

array([21, 22, 23, 24, 25])

### 17. Écrire le code qui reproduit la sortie montrée ci-dessous

In [20]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Ne pas exécuter cette cellule

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Opérations NumPy

### 18. Obtenir la somme de toutes les valeurs de mat

In [21]:
np.sum(mat)

325

In [ ]:
# Ne pas exécuter cette cellule

325

### 19. Obtenir l'écart type des valeurs de mat

In [22]:
np.std(mat)

7.211102550927978

In [ ]:
# Ne pas exécuter cette cellule

7.211102550927978

### 20. Obtenir la somme de toutes les colonnes de mat

In [23]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Ne pas exécuter cette cellule

array([55, 60, 65, 70, 75])

## Question Bonus

Nous allons beaucoup travailler avec des données aléatoires avec NumPy, mais existe-t-il un moyen de s'assurer que nous obtenons toujours les mêmes nombres aléatoires ? [Cliquez ici pour un indice](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

**Bon courage !**